<?php
if(isset($_POST['submit'])){
    $name=$_POST['name'];
    $email=$_POST['email'];
    $phone=$_POST['phone'];
    $subject=$_POST['subject'];
    $message=$_POST['message'];
    $to="alienramzi@gmail.com";
    $header="from:$email";
    if(mail($to,$subject,$message,$header)){
        $msg1="Succes!"
    }
}